caption_model: newfc
input_json: data/cocotalk.json
input_fc_dir: data/cocobu_fc
input_att_dir: data/cocobu_att
input_label_h5: data/cocotalk_label.h5

learning_rate: 0.0005

save_checkpoint_every: 3000
val_images_use: 5000

batch_size: 10
max_epochs: 30
